Fixes #195 add chronological sorting to home page, user/org profile page
pytition/Pytition pull request #261
Opened 2020-10-17 13:15 UTC by toshihidetagami

Fixes #195

- This pull request adds chronological sorting to the Home page, User profile page, organization page.
- "creation_date" is used for sorting
- I initially planned to use drop-down for sorting. But I chose "segmented button" because I think it looks nicer on UI and the code will be simpler.

I am happy to fix or refactor if there are any problems with code, UI, etc.

**Orgnization Profile Page**
![Screen Shot 2020-10-17 at 8 53 47 PM](https://user-images.githubusercontent.com/4319619/96337640-2758ec80-10bb-11eb-986f-59588a6f2f59.png)

**User Profile Page**
![Screen Shot 2020-10-17 at 8 54 09 PM](https://user-images.githubusercontent.com/4319619/96337646-2b850a00-10bb-11eb-9a9e-20d342ec9828.png)

**Home Page**
![Screen Shot 2020-10-17 at 8 54 45 PM](https://user-images.githubusercontent.com/4319619/96337649-2de76400-10bb-11eb-8439-fbe504d1e883.png)

2020-10-17 13:27 UTC, fallen requested changes
This PR looks very good, thanks!
Pictures are :+1: 
One minor change to allow texts to be translated and I can merge this :)

2020-10-17 13:27 UTC, fallen commented on pytition/petition/templates/petition/index.html
> +              href="{% url "index" %}?sort=desc#petition-list-id" role="button">Last Created</a>
You need to use {% trans "Last Created" %} for all texts so that they can be translated

2020-10-18 05:35 UTC, toshihidetagami commented
I just added a commit for the translation!

2020-10-18 10:45 UTC, fallen approved these changes
Looks good to me, merging!
Thanks :+1:

2020-10-18 10:46 UTC, merged